### ISSUE TITLE
Dependencies: Coordinate Charmbracelet ecosystem update (fang, lipgloss, log, x/*)

### ISSUE THREAD

**Issue by unclesp1d3r** [EvilBit-Labs/opnDossier#146]
## Summary

The Charmbracelet dependencies need a coordinated update. Updating `fang` alone causes API incompatibilities with `lipgloss` and `log` packages.

## Current Versions

| Package | Current | Latest |
|---------|---------|--------|
| `charmbracelet/fang` | v0.3.0 | v0.4.4 |
| `charmbracelet/lipgloss` | v1.1.1-0.20250404203927-76690c660834 | (needs coordination) |
| `charmbracelet/log` | v0.4.2 | (needs coordination) |
| `charmbracelet/bubbles` | v0.21.0 | (check compatibility) |
| `charmbracelet/glamour` | v0.10.0 | (check compatibility) |
| `charmbracelet/x/ansi` | v0.10.1 | v0.11.3 |
| `charmbracelet/x/cellbuf` | v0.0.13 | v0.0.14 |
| `charmbracelet/x/term` | v0.2.1 | v0.2.2 |

## Problem

When updating `fang` to v0.4.4 independently, the following errors occur:

```
github.com/charmbracelet/x/cellbuf@v0.0.13/cell.go:200:8: not enough arguments in call to b.Italic
github.com/charmbracelet/x/cellbuf@v0.0.13/cell.go:203:10: b.SlowBlink undefined
github.com/charmbracelet/x/cellbuf@v0.0.13/cell.go:206:8: not enough arguments in call to b.RapidBlink
...
internal/log/logger.go:137:27: l.With undefined (type *Logger has no field or method With)
```

This indicates breaking changes in the `ansi.Style` API that affect `cellbuf`, which in turn affects `lipgloss` and `log`.

## Required Approach

1. **Research compatible versions** - Check Charmbracelet release notes for compatible version combinations
2. **Update all packages together** - Cannot update incrementally
3. **Review API changes** - Check if our code uses any changed APIs in:
   - `internal/log/logger.go` - Uses `log.Logger.With()`
   - `internal/display/display.go` - Uses `lipgloss` styling
   - `cmd/*.go` - Uses `fang` for CLI enhancement

## Files to Review

- `internal/log/logger.go` - Logger wrapper
- `internal/display/display.go` - Terminal display/themes
- `internal/display/theme.go` - Theme management
- `cmd/root.go` - CLI setup with fang

## Fang v0.4.x Changelog

From v0.4.0:
- feat: handle redirects in examples
- fix: command alias styling
- fix: spacing in help for default value

These are bug fixes, not breaking changes to our usage.

## Testing Required

- [ ] All existing tests pass
- [ ] CLI help output renders correctly
- [ ] Logging with context/fields works
- [ ] Terminal theming works (dark/light/auto)
- [ ] Progress bars display correctly

## Priority

Low - Current versions work correctly. This is a maintenance update.

---
*Generated from dependency review*
